//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_WebApplication14_EntityModel_Project1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public string Eid { get; set; }
        public int Sid { get; set; }
        public int Cid { get; set; }
        public System.DateTime DOA { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }
    }
}
